  filter_ignore_branches: &filter_ignore_branches
    filters:
      branches:
        ignore: /.*/
  filter_ignore_dev_release_branches: &filter_ignore_dev_release_branches
    filters:
      branches:
        ignore: /^(dev|release).*/

  setup_remote_docker: &setup_remote_docker
    setup_remote_docker:
      version: 19.03.13
      docker_layer_caching: true

  # ref pg environment for testing
  test_pg_env: &test_pg_env
    environment:
      SERVER_URL: localhost
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretsecretadminpassword
      POSTGRES_DB: gql_test
      PGPORT: 5432